#
# Copyright (c) 2019 Wee Loong Kuan
#
# Part of BareMetalLib, under the Apache License v2.0 with LLVM Exceptions. See
# https://llvm.org/LICENSE.txt for license information.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

FROM arm32v5/debian:buster-slim

# Enable the container to be run on (properly-configured) non-ARMv7 hosts via QEMU user emulation.
COPY qemu-arm-static /usr/bin/qemu-arm-static

RUN apt-get update
RUN apt-get -y install --no-install-recommends cmake make clang-6.0 g++-8

RUN mkdir -p /bml/src
RUN mkdir -p /bml/build
WORKDIR /bml/build

CMD ["/bin/bash", "-c", \
     "cmake -DBML_BUILD_TESTS=ON -DBML_TESTBENCH_ARCH=armv5l ../src && make && ctest"]
