#
# Copyright (c) 2019 Wee Loong Kuan
#
# Part of BareMetalLib, under the Apache License v2.0 with LLVM Exceptions. See
# https://llvm.org/LICENSE.txt for license information.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

FROM i386/debian:buster-slim

RUN apt-get update
RUN apt-get -y install --no-install-recommends cmake make clang-6.0 g++-8

RUN mkdir -p /bml/src
RUN mkdir -p /bml/build
WORKDIR /bml/build

CMD ["/bin/bash", "-c", \
     "cmake -DBML_BUILD_TESTS=ON -DBML_TESTBENCH_ARCH=i386 ../src && make && ctest"]
