#
# Copyright (c) 2019 Wee Loong Kuan
#
# Part of BareMetalLib, under the Apache License v2.0 with LLVM Exceptions. See
# https://llvm.org/LICENSE.txt for license information.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

FROM arm64v8/debian:buster-slim

# Enable the container to be run on (properly-configured) non-aarch64 hosts via QEMU user emulation.
COPY qemu-aarch64-static /usr/bin/qemu-aarch64-static

RUN apt-get update
RUN apt-get -y install --no-install-recommends cmake make clang-6.0 g++-8

RUN mkdir -p /bml/src
RUN mkdir -p /bml/build
WORKDIR /bml/build

CMD ["/bin/bash", "-c", "cmake -DBML_BUILD_TESTS=ON ../src && make && ctest"]
