#
# Copyright (c) 2019 Wee Loong Kuan
#
# Part of BareMetalLib, under the Apache License v2.0 with LLVM Exceptions. See
# https://llvm.org/LICENSE.txt for license information.
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

language: cpp

os: linux
dist: xenial
sudo: required
services:
  - docker

env:
  - DOCKER_CXX: /usr/bin/clang++-6.0
    DOCKER_TAG: linux-x86_64
  - DOCKER_CXX: /usr/bin/g++-8
    DOCKER_TAG: linux-x86_64
  - DOCKER_CXX: /usr/bin/clang++-6.0
    DOCKER_TAG: linux-i386
  - DOCKER_CXX: /usr/bin/g++-8
    DOCKER_TAG: linux-i386
  - DOCKER_CXX: /usr/bin/clang++-6.0
    DOCKER_TAG: linux-aarch64
  - DOCKER_CXX: /usr/bin/g++-8
    DOCKER_TAG: linux-aarch64
  - DOCKER_CXX: /usr/bin/clang++-6.0
    DOCKER_TAG: linux-armv7l
  - DOCKER_CXX: /usr/bin/g++-8
    DOCKER_TAG: linux-armv7l
  - DOCKER_CXX: /usr/bin/clang++-6.0
    DOCKER_TAG: linux-armv5l
  - DOCKER_CXX: /usr/bin/g++-8
    DOCKER_TAG: linux-armv5l

before_install:
  - sudo apt-get install -y binfmt-support qemu-user-static
  - sudo docker pull kuanweeloong/bml-build:${DOCKER_TAG}
  - >-
    sudo docker create --rm --name bml-travis --env CXX=${DOCKER_CXX}
    kuanweeloong/bml-build:${DOCKER_TAG}
  - sudo docker cp . bml-travis:/bml/src/

script:
  - sudo docker start --attach bml-travis
